spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?serverTimezone=Asia/Shanghai
    username: root
    password: Mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"'
      aop-patterns: com.atguigu.admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false
  jdbc:
    template:
      fetch-size: 3
      query-timeout: 10
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
info:
  app: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@
